### PR TITLE
v0.2.0

### PR DESCRIPTION
**Pull request by paraynaud**
Include:
- Project.toml version 0.2.0;
- Small fixes in README.md;
- Add some text from the README.md in the HOME (docs/index.md) of the documentation.

### CODE REVIEW

**Comment by dpo** [comment]
Why aren't the Cirrus tests running?

**Comment by paraynaud** [comment]
It says that my account is suspended :/

**Comment by dpo** [comment]
your cirrus account?

**Comment by paraynaud** [comment]
Yes, i don't know why.

**Comment by dpo** [comment]
Mine too :-(
Some automated system is casting a wide net.

**Review by dpo — APPROVED** [review]

**Comment by dpo** [comment]
thank you

**Pull request merged**
