### PR TITLE
JOSS article

### PR DESCRIPTION
**Pull request by paraynaud**
JOSS article branch.

### CODE REVIEW

**Comment by paraynaud** [comment]
See the [guidelines](https://joss.readthedocs.io/en/latest/submitting.html).

See examples:
- [Gala example](https://github.com/adrn/gala)
- [CDISolvers](https://github.com/JuliaSmoothOptimizers/DCISolver.jl/tree/joss-paper-branch)

**Comment by paraynaud** [comment]
@dpo, I added a github action `draft-pdf.yml` compiling the PDF for each push.
The gh action works fine, but I can't get (i don't know where it is) the .pdf as an artifact as it should be the case [see JOSS gh action](https://github.com/marketplace/actions/open-journals-pdf-generator).

**Comment by dpo** [comment]
Click on "Details" next to the "draft-pdf" check in this PR, then click on "Summary" (top left). You'll see the paper in the "Artifacts" section at the bottom.

It would make sense to remove the other actions from this branch.

**Comment by paraynaud** [comment]
@farhadrclass now that R2 is implemented, we should have a good example for the paper!

I checked R2 code, If we define a callback function:
```julia
function callback(knetnlp, solver, stats)
  reset_minibatch_train!(knetnlp)
  return nothing
end
```
it should allow R2 to be a sctochastic training for the network modelized by `knetnlp`.

**Comment by farhadrclass** [comment]
@paraynaud  also I created a whole new project for examples, https://github.com/farhadrclass/KnetNLPModelsProblems/tree/main let me know if you like to use any of them

**Comment by paraynaud** [comment]
I still don't get why you keep only the `best_acc`, but you should add an optionnal argument to not return `endFlag` in `reset_minibatch_train_next`.
Also, I don't understand the use of `data_buff `.

**Comment by farhadrclass** [comment]
> I still don't get why you keep only the `best_acc`, but you should add an optionnal argument to not return `endFlag` in `reset_minibatch_train_next`. Also, I don't understand the use of `data_buff `.

best_acc is usually used to save an intermediate model to file, which I have not done the write to file yet, It is a way to save progress if something went wrong with large data and when you restart, you can start from last best_acc model's weight 

data_buff was an old code, good point, I removed it 

The flag is removed already but I need to update the code, I suggest we include the reset_minibatch_train_next! in the knetnlpmodels as it will be more useful there no?

**Comment by paraynaud** [comment]
I am confused between what is still relevant in your code or not.
Mention me when you open your PR, I will review you at this moment.

```quote
The flag is removed already but I need to update the code, I suggest we include the reset_minibatch_train_next! in the knetnlpmodels as it will be more useful there no?
```
I don't see any issues to your suggestion (switch to next batch instead of a random one).
I tried `iterate(nlp.current_training_minibatch)` but I ended up with an error.

**Comment by farhadrclass** [comment]
@paraynaud I updated my code on https://github.com/farhadrclass/KnetNLPModelsProblems/tree/main, I am getting small error now that R2 stops after 10 iteration, need to check why but should be done with it soon

**Comment by paraynaud** [comment]
The best way to proceed is to make a pull-request for any new changes and request a review from people related to it when it is ready.
It is also a lot easier to review code changes from several commits inside a pull request.

**Comment by farhadrclass** [comment]
@paraynaud  thanks for suggestion and help 
I was thinking the KnetnlpProblems should be a stand alone repo similar to the nlpProblems but we can select some of the problems to be added to knetnlpmodels as examples no?

I will select some examples with also new methods and create 2 PR for knetnlpmodels since I know @dpo  prefer to decouple the PR 
1. PR 1 for utilities function
2. PR 2 for examples
Should be done with code cleaning and experiment by Friday and will create the shortly
what do you think?

**Comment by paraynaud** [comment]
```quote
I was thinking the KnetnlpProblems should be a stand alone repo similar to the nlpProblems
```
Yes.

```quote
 but we can select some of the problems to be added to knetnlpmodels as examples no?
```
No, because KnetNLPProblems depends of KnetNLPModels, KnetNLPModels will not depend of KnetNLPProblems (it becomes circular).
If you want to add some tests, you can copy-paste some KnetNLPProblems code, but not add it as a dependency.

Let's start with PR1, which should add a new way to change the training minibatch.

**Comment by paraynaud** [comment]
You can replace the current `reset_training_minibatch!` with your code, but keep the code of the current one as a new method `rand_training_minibatch!`.
That way we get more tools to work aound KnetNLPModels!

**Comment by farhadrclass** [comment]
I created the PR with the minibatch reset, however, I suggest we create 3 functions:

- random
- first 
- next 
this way user can reset it when they need

**Comment by paraynaud** [comment]
I don't see the PR right now, but I agree with your suggestion.

**Comment by farhadrclass** [comment]
I think my github has a sync problem 
here is the PR https://github.com/JuliaSmoothOptimizers/KnetNLPModels.jl/pull/57
let me know what you think

**Comment by farhadrclass** [comment]
I also did it for the test mini-batch even though we may not use it right now

**Comment by paraynaud** [comment]
> I also did it for the test mini-batch even though we may not use it right now

Thanks.
For now, the test minibatch is there just in case.
`accuracy(knetnlp)` doesn't use it.

**Pull request closed without merging**
